### ISSUE TITLE
Crash on player join

### ISSUE THREAD

**Issue by ndrnmnk** [LekmaDev/BS-26#3]
$ sh core.sh
Server | Lobby started! 0.0.0.0:9339
Server | Battle started! 0.0.0.0:6969
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/andrey/BS-26/core.py", line 94, in run
    message.process()
  File "/home/andrey/BS-26/Client/Login/LoginMessage.py", line 55, in process
    FriendListMessage(self.client, self.player).send()
  File "/home/andrey/BS-26/Utils/Writer.py", line 43, in send
    self.encode()
  File "/home/andrey/BS-26/Server/Friend/FriendListMessage.py", line 18, in encode
    friends_json = user[22]
TypeError: 'NoneType' object is not subscriptable

**Comment by ndrnmnk** [comment]
I changed the database, now client crashes, but not the server

**Comment by for0si0zero** [comment]
> I changed the database, now client crashes, but not the server

give me pls database 22

**Comment by ndrnmnk** [comment]
@for0si0zero 
OK, but online battles are super laggy, and you cant create club (it says to win 1 battle, and after doing so nothing changes)
https://drive.google.com/drive/folders/16hz1829BwyUtzE_uj8Bse6Lmjf2L5Yff?usp=drive_link

**Comment by MinecAnton209** [comment]
How fix Database locked problem when i restart server?

**Comment by ndrnmnk** [comment]
@MinecAnton209 it means that database gets corrupted. Disconnect all clients, wait 10 seconds and only then power off the server.
