### ISSUE TITLE
Error: sqlite3.OperationalError: table plrs has 32 columns but 27 values were supplied

### ISSUE THREAD

**Issue by OldMarket26** [LekmaDev/BS-26#4]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "<string>", line 94, in run
  File "/storage/emulated/0/Download/BS-26-main/Client/Login/LoginMessage.py", line 41, in process
    DataBase.createAccount(self)
  File "/storage/emulated/0/Download/BS-26-main/database/DataBase.py", line 67, in createAccount
    self.cur.execute("INSERT INTO plrs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", var)
sqlite3.OperationalError: table plrs has 32 columns but 27 values were supplied

**Comment by ghost** [comment]
discussed in #3
