### ISSUE TITLE
Issue on Android 13

### ISSUE THREAD

**Issue by SomeDuckOnEarth** [LekmaDev/BS-26#6]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 6, in <module>
  File "/storage/emulated/0/Download/BS-26-main/BS-26-main/database/DataBase.py", line 4, in <module>
    from tinydb import TinyDB, Query, database
ModuleNotFoundError: No module named 'tinydb'

[Program finished]

**Comment by MinecAnton209** [comment]
This is not problem with android you not have module TinyDB
Fix: in terminal(NOT INTERPRETER) `pip install tinydb`
